version: '3'

networks:
  ansible-formation:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.21.1.0/16"

services:
  ubuntu01:
    image: albttx/ubuntu-sshd:18.04
    restart: unless-stopped
    networks:
      ansible-formation:
        ipv4_address: "172.21.1.4"
    ports:
      - "22:22"
      - "8080:8080"
