- hosts: 127.0.0.1
  connection: local
  gather_facts: False
  vars:
    name: Groot
    date_of_birth: "1993-11-10"
    skills: ["Ansible", "Docker", "Kubernetes"]
    driver_license: True
  roles:
    - "roles/resume"
